# This Cleaner instance finds all ConfigMaps instances in
# the namespace *bar* which are orphaned. Orphaned here means a ConfigMap that is not used by:
# - Pod through volumes (pod.spec.volumes)
# - Pod through environment variables (pod.spec.containers.env and pod.spec.containers.envFrom)
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: completed-pods
spec:
  schedule: "* 0 * * *"
  dryRun: false
  resourcePolicySet:
    resourceSelectors:
    - namespace: bar
      kind: Pod
      group: ""
      version: v1
    - namespace: bar
      kind: ConfigMap
      group: ""
      version: v1   
    action: Delete
    aggregatedSelection: |
      function configMapsUsedByPods(pods)
        local podConfigMaps = {}

        for _, pod in ipairs(pods) do
          if pod.spec.containers ~= nil then
            for _, container in ipairs(pod.spec.containers) do
              
              if container.env ~= nil then
                for _, env in ipairs(container.env) do
                  if env.valueFrom ~= nil and env.valueFrom.configMapKeyRef ~= nil then
                    podConfigMaps[env.valueFrom.configMapKeyRef.name] = true
                  end
                end
              end

              if container.envFrom ~= nil then
                for _, envFrom in ipairs(container.envFrom) do
                  if envFrom.configMapRef ~= nil then
                    podConfigMaps[envFrom.configMapRef.name] = true
                  end
                end
              end  
            end
          end

          if pod.spec.initContainers ~= nil then
            for _, initContainer in ipairs(pod.spec.initContainers) do

              if initContainer.env ~= nil then
                for _, env in ipairs(initContainer.env) do
                  if env.valueFrom ~= nil and env.valueFrom.configMapKeyRef ~= nil then
                    podConfigMaps[env.valueFrom.configMapKeyRef.name] = true
                  end
                end
              end

              if initContainer.envFrom ~= nil then
                for _, envFrom in ipairs(initContainer.envFrom) do
                  if envFrom.configMapRef ~= nil then
                    podConfigMaps[envFrom.configMapRef.name] = true
                  end
                end
              end  

            end
          end    

          if pod.spec.volumes ~= nil then  
            for _, volume in ipairs(pod.spec.volumes) do
              if volume.configMap ~= nil then
                podConfigMaps[volume.configMap.name] = true
              end

              if volume.projected ~= nil and volume.projected.sources ~= nil then
                for _, projectedResource in ipairs(volume.projected.sources) do
                  if projectedResource.configMap ~= nil then
                    podConfigMaps[projectedResource.configMap.name] = true
                  end
                end
              end
            end
          end
        end  

        return podConfigMaps
      end

      function evaluate()
        local hs = {}
        hs.valid = true
        hs.message = ""

        local pods = {}
        local configMaps = {}
        local unusedConfigMaps = {}

        -- Separate configMaps and podsfrom the resources
        for _, resource in ipairs(resources) do
            local kind = resource.kind
            if kind == "ConfigMap" then
              table.insert(configMaps, resource)
            elseif kind == "Pod" then
              table.insert(pods, resource)
            end
        end

        podConfigMaps = configMapsUsedByPods(pods)

        for _, configMap in ipairs(configMaps) do
          if not podConfigMaps[configMap.metadata.name] then
            table.insert(unusedConfigMaps, configMap)
          end
        end

        hs.resources = unusedConfigMaps
        return hs
      end