# permissions for end users to view pruners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pruner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-pruner
    app.kubernetes.io/part-of: k8s-pruner
    app.kubernetes.io/managed-by: kustomize
  name: pruner-viewer-role
rules:
- apiGroups:
  - apps.projectsveltos.io
  resources:
  - pruners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.projectsveltos.io
  resources:
  - pruners/status
  verbs:
  - get
