{{- if $.Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  name: {{ include "k8s-cleaner.fullname" . }}-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps.projectsveltos.io
  resources:
  - cleaners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.projectsveltos.io
  resources:
  - cleaners/finalizers
  verbs:
  - update
- apiGroups:
  - apps.projectsveltos.io
  resources:
  - cleaners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.projectsveltos.io
  resources:
  - reports
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  name: {{ include "k8s-cleaner.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  name: {{ include "k8s-cleaner.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  name: {{ include "k8s-cleaner.fullname" . }}-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-cleaner.fullname" . }}-controller-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-cleaner.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
  name: {{ include "k8s-cleaner.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-cleaner.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-cleaner.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}