apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-cleaner.fullname" . }}-metrics
  labels:
    {{- include "k8s-cleaner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "k8s-cleaner.selectorLabels" . | nindent 4 }}
